spring:
  r2dbc:
    password: root
    username: root
    url: r2dbc:mysql://localhost:3306/school_manage
    name: school_manage
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN
  main:
    allow-circular-references: true

logging:
  level:
    org.springframework:
      r2dbc: DEBUG